### ISSUE TITLE
Generated configuration contains 'backend' which is not a valid configuration option?

### ISSUE THREAD

**Issue by pvandervelde** [johnbellone/vault-cookbook#100]
With my cookbook attributes looking like this:

    default['hashicorp-vault']['version'] = '0.7.3'

    default['hashicorp-vault']['config']['habackend_type'] = 'consul'
    default['hashicorp-vault']['config']['habackend_options']['address'] = '127.0.0.1:8500'
    default['hashicorp-vault']['config']['habackend_options']['check_timeout'] = '10s'
    default['hashicorp-vault']['config']['habackend_options']['disable_registration'] = false
    default['hashicorp-vault']['config']['habackend_options']['path'] = 'vault/'
    default['hashicorp-vault']['config']['habackend_options']['scheme'] = 'http'

    default['hashicorp-vault']['config']['tls_disable'] = true

I get a configuration that looks like this:

    {
      "disable_mlock": false,
      "listener": {
        "tcp": {
          "address": "127.0.0.1:8200",
          "tls_disable": "true"
        }
      },
      "backend": {
        "inmem": {
        }
      },
      "ha_backend": {
        "consul": {
          "address": "127.0.0.1:8500",
          "check_timeout": "10s",
          "disable_registration": false,
          "path": "vault/",
          "scheme": "http"
        }
      }
    }

Vault complains that:

    Error loading configuration from /etc/vault/vault.json: error parsing 'ha_backend': ha_backend.consul: At -: root.disable_registration: unknown type for string *ast.LiteralType

But if I change `ha_backend` to `storage` everything works. However `storage` is not a valid configuration option (see #95). So how do I get the cookbook to generate the correct configuration file?

**Comment by legal90** [comment]
Confirmed. Seems like `ha_backend` was renamed to `ha_storage`
https://github.com/hashicorp/vault/pull/2471
