### ISSUE TITLE
Spec test issue for vault_config: Chef::Provider does not implement #chef_vault_item

### ISSUE THREAD

**Issue by jeffbyrnes** [johnbellone/vault-cookbook#11]
It seems the Rspec tests have been broken for a while, as a number of them issue this failure: `Chef::Provider does not implement #chef_vault_item`

See [lines 316–9 of Travis CI Job#21.2](https://travis-ci.org/johnbellone/vault-cookbook/jobs/75500081#L316-L319) for an example.

**Comment by jeffbyrnes** [comment]
As it turns out, in some cases, these tests will pass just fine. I _think_ it has something to do with the randomized nature of the tests, but it’s difficult to tell.

**Comment by marc-** [comment]
Running cookbook with TLS enabled just doesn't work.
```
 ================================================================================
Error executing action `create` on resource 'vault_config[/home/vault/.vault.json]'
================================================================================
NoMethodError
-------------
No resource or method named `chef_vault_item' for `VaultCookbook::Resource::VaultConfig (fused) ""'
```
Chef version 12.4.3-1 .

**Comment by jeffbyrnes** [comment]
@marc- sounds like a separate issue; mind filing that separately?

**Comment by marc-** [comment]
Sure.
