### ISSUE TITLE
No method chef_vault_item

### ISSUE THREAD

**Issue by lfrodrigues** [johnbellone/vault-cookbook#24]
Hello,
I'm getting ```No resource or method named `chef_vault_item' for `VaultCookbook::Resource::VaultConfig (fused) ""'"```
Any idea what I could be doing wrong? I'm using the recipes from your vault-cluster-cookbook

**Comment by lfrodrigues** [comment]
I disabled the manager certs and fixes this, not the best solution but lets me install and configure everything

**Comment by marc-** [comment]
Please see #21 . In shot, you have to update `chef-vault` cookbook to 1.3.0.
