### ISSUE TITLE
metadata updates

### ISSUE THREAD

**Issue by blairham** [johnbellone/vault-cookbook#33]
When you bump the vault version in the attributes, is it at all possible to bump the last number in your cookbook version in your metadata? 

This is extremely important for berks and version locking.

**Comment by sh9189** [comment]
Yes, we do bump the cookbook version (major/minor/patch) before the cookbook is released to supermarket. You can see the latest release [1.5.0] (https://github.com/johnbellone/vault-cookbook/releases/tag/v1.5.0) bumped up the minor version.

**Comment by johnbellone** [comment]
@blairham Are you deploying directly from this repository?

**Comment by johnbellone** [comment]
Alright, I agree that we should be bumping the release of the cookbook each time that its updated inside of the attributes. That is generally the case. But there are times you're going to hit a lag time between the actual tag/release. The best way to do this would be to get your releases from the [Chef Supermarket](https://supermarket.chef.io).
