### ISSUE TITLE
Error executing action `create` on resource 'vault_config[/home/vault/.vault.json]'

### ISSUE THREAD

**Issue by CodeGnome** [johnbellone/vault-cookbook#39]
## Error with Default Recipe
The README doesn't document any special configuration instructions. Including the cookbook via Berkshelf and adding the recipe to the run_list results in the following errors:

    ==> default: ================================================================================
    ==> default:     
    ==> default: Error executing action `create` on resource 'vault_config[/home/vault/.vault.json]'
    ==> default:     
    ==> default: ================================================================================
    ==> default:     
    ==> default: 
    ==> default: 
    ==> default:     
    ==> default: NoMethodError
    ==> default:     
    ==> default: -------------
    ==> default:     
    ==> default: undefined method `delete' for nil:NilClass
    ==> default:     
    ==> default: 
    ==> default: 
    ==> default:     
    ==> default: Cookbook Trace:
    ==> default:     
    ==> default: ---------------
    ==> default:     
    ==> default: /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/chef-vault/libraries/helpers.rb:36:in `chef_vault_item'
    ==> default: 
    ==> default:     
    ==> default: /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/hashicorp-vault/libraries/vault_config.rb:77:in `block (2 levels) in <class:VaultConfig>'
    ==> default: 
    ==> default:     
    ==> default: /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
    ==> default: 
    ==> default:     
    ==> default: /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
    ==> default: 
    ==> default:     
    ==> default: /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
    ==> default:     /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/hashicorp-vault/libraries/vault_config.rb:67:in `block in <class:VaultConfig>'
    ==> default:     
    ==> default:     Resource Declaration:
    ==> default:     ---------------------
    ==> default:     # In /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/hashicorp-vault/recipes/default.rb
    ==> default:     
    ==> default:      11: config = vault_config node['vault']['config']['path'] do |r|
    ==> default:      12:   owner node['vault']['service_user']
    ==> default:      13:   group node['vault']['service_group']
    ==> default:      14: 
    ==> default:      15:   node['vault']['config'].each_pair { |k, v| r.send(k, v) }
    ==> default:      16:   notifies :restart, "vault_service[#{node['vault']['service_name']}]", :delayed
    ==> default:      17: end
    ==> default:      18: 
    ==> default:     
    ==> default:     Compiled Resource:
    ==> default:     ------------------
    ==> default:     # Declared in /tmp/vagrant-chef/48858a378e29c892aa9eae9959029b86/cookbooks/hashicorp-vault/recipes/default.rb:11:in `from_file'
    ==> default:     
    ==> default:     vault_config("/home/vault/.vault.json") do
    ==> default:       provider #<Class:0x000000025d2080>
    ==> default:       action [:create]
    ==> default:       retries 0
    ==> default:       retry_delay 2
    ==> default:       default_guard_interpreter :default
    ==> default:       declared_type :vault_config
    ==> default:       cookbook_name :"hashicorp-vault"
    ==> default:       recipe_name "default"
    ==> default:       owner "vault"
    ==> default:       group "vault"
    ==> default:       path "/home/vault/.vault.json"
    ==> default:       address "127.0.0.1:8200"
    ==> default:       manage_certificate true
    ==> default:       tls_cert_file "/etc/vault/ssl/certs/vault.crt"
    ==> default:       tls_key_file "/etc/vault/ssl/private/vault.key"
    ==> default:       tls_disable "false"
    ==> default:       bag_name "secrets"
    ==> default:       bag_item "vault"
    ==> default:     end

## Expected Behavior
The recipe should either run in some vanilla configuration out of the box, or any *required* attributes or configuration settings should be documented in the README.

**Comment by sh9189** [comment]
Which platform/ cookbook version is this on? I tried the latest cookbook version on both centos 7.1/ubuntu 14.04 and the default recipe converged successfully on test kitchen.

**Comment by CodeGnome** [comment]
## Cookbook Versions
The cookbook is defined within a top-level Berksfile as:

    cookbook 'hashicorp-vault', '~> 1.5.0'

The cookbook was added to the run_list as "hashicorp-vault" even though the supermarket source link points to "vault-cookbook" instead.

## OS Versions
The host is OS X 10.11.3 (El Capitan), but the Vagrant box is Ubuntu 14.04.3 LTS. The Vagrantfile defines:

    config.vm.box = 'ubuntu/trusty64'

Not only does it not work within a Vagrantfile, test kitchen also fails to converge:

>     I, [2016-02-16T11:37:18.583001 #59239]  INFO -- Kitchen: -----> Converging <install-from-source-ubuntu-1404>...
>     E, [2016-02-16T11:38:40.413398 #59239] ERROR -- Kitchen: Converge failed on instance <install-from-source-ubuntu-1404>.

## Other Software Versions
    $ vagrant --version
    Vagrant 1.8.1

    $ vboxmanage --version
    5.0.14r105127

    $ vagrant plugin list | fgrep berkshelf
    vagrant-berkshelf (4.1.0)

**Comment by sh9189** [comment]
The default recipe needs a tls key and cert as a chef-vault item. This is supplied using a data bag item as seen [here] (https://github.com/johnbellone/vault-cookbook/blob/master/test/integration/data_bags/secrets/vault.json) for test kitchen.
Alternatively you can also disable tls by setting the following attribute
`default['vault']['config']['tls_disable'] = 'true'`

**Comment by johnbellone** [comment]
We should probably make it clear in the documentation that it is necessary to disable this in order to converge without providing a certificate... even if it is invalid.

**Comment by CodeGnome** [comment]
On a related note (should I open a separate issue?) if `'tls_disable = true` the recipe blows up because it's expecting a string. It really ought to be more flexible and accept `true`, coercing to String if necessary. If that's something you are willing to do, I can see about making a PR request for that.

**Comment by CodeGnome** [comment]
The error and its work-around has been [documented on the wiki](https://github.com/johnbellone/vault-cookbook/wiki#known-errors).

**Comment by johnbellone** [comment]
This has been updated in latest master branch set of commits and will be released as 2.0.
