### ISSUE TITLE
tls_disable attribute only accepts strings

### ISSUE THREAD

**Issue by CodeGnome** [johnbellone/vault-cookbook#40]
When `'tls_disable' = true`, the recipe blows up because it's expecting a String rather than a Boolean or Fixnum. The attribute parser really ought to be more flexible and accept:

- `true`
- `false`
- `0`
- `1`

and then coerce to String if necessary to fit Vault's expectations. Pull request to follow.

**Comment by johnbellone** [comment]
This has been updated in latest master branch set of commits and will be released as 2.0.
