### ISSUE TITLE
Getting warning message in Chef run

### ISSUE THREAD

**Issue by nilroy** [johnbellone/vault-cookbook#46]
Hi,

I am using chef 12.4.0 and I am getting warning message like below:

`[2016-03-14T14:49:37+00:00] WARN: You declared a new resource PoiseService::ServiceProviders::Inittab for resource poise_service, but it comes alphabetically after PoiseService::ServiceProviders::Dummy and has the same filters ({}), so it will not be used. Use override: true if you want to use it for poise_service.`

How do I get rid of them?

**Comment by johnbellone** [comment]
/cc @coderanger

I believe these messages go away in a newer version of Chef Client?

**Comment by coderanger** [comment]
That was fixed in 12.5 I think. It was a bug when the warning was added.

**Comment by nilroy** [comment]
I shall try 12.5 then
