### ISSUE TITLE
Vault service fails to start

### ISSUE THREAD

**Issue by zarry** [johnbellone/vault-cookbook#5]
Vault service is not starting properly.  Looks like it requires root access but we run it as the vault user?  @johnbellone how are you tackling this?  I grabbed this snippet from the /etc/init/vault.conf.  

Have any way we can chat re: this?  Maybe slack? I am on the chef-brigade channel. https://brigade-slackin.herokuapp.com/

```
% sudo su -c "vault server -config=/home/vault/.vault.json" -s /bin/sh vault
Error initializing core: Failed to lock memory: cannot allocate memory

This usually means that the mlock syscall is not available.
Vault uses mlock to prevent memory from being swapped to
disk. This requires root privileges as well as a machine
that supports mlock. Please enable mlock on your system or
disable Vault from using it. To disable Vault from using it,
set the `disable_mlock` configuration option in your configuration
file.
```

Side Note: I worked around this issue by setting the service_user to root in my wrapper cookbook.  Mostly asking if this should be the default as opposed to vault that is currently the default.

**Comment by johnbellone** [comment]
I'll take a look into this. I think I have a working case locally.
