### ISSUE TITLE
Specifying 'root' removes root login shell

### ISSUE THREAD

**Issue by rpattcorner** [johnbellone/vault-cookbook#53]
So, if you override the `default['hashicorp-vault']['service_user'] = 'vault'` and decide to run as:

`['hashicorp-vault']['service_user'] = 'root'` via an override or whatever, you'll become unable to operate as root on next login.

Probably because the config process turns the root user into a service account.  Your entry in passwd winds up looking like:

`root:x:0:0:Service user for root:/root:/bin/false`

**Comment by johnbellone** [comment]
Ha, that sucks, nice catch. I'll fix that.
