### ISSUE TITLE
Service doesn't come back after reboot because the default service directory is missing

### ISSUE THREAD

**Issue by Fitzsimmons** [johnbellone/vault-cookbook#55]
The default service directory is `/var/run/vault`, which is created by the cookbook - but on many systems, `/var/run` is mounted as tmpfs. This means that `/var/run/vault` is not present if the server reboots. The creation of `/var/run/vault` should be the responsibility of the init script, so that we don't run into this problem.

**Comment by johnbellone** [comment]
What platform/version are you running?

**Comment by Fitzsimmons** [comment]
I'm running Ubuntu 14.04. The issue is worse when using sysv, because it has nowhere to put the pidfile. When using upstart, a pidfile is not needed, but it will still attempt to chdir to `/var/run/vault` and crash when that directory doesn't exist; in this case, `node['hashicorp-vault']['service']['directory']` can be overridden to anything persistent, like `/etc/vault`.

**Comment by legal90** [comment]
For `sysvinit` it was fixed by https://github.com/johnbellone/vault-cookbook/pull/51
