### ISSUE TITLE
Vault archive download address should be configurable

### ISSUE THREAD

**Issue by cevn** [johnbellone/vault-cookbook#74]
Something like https://github.com/johnbellone/consul-cookbook/issues/342

If it is configurable, then document it somewhere?

**Comment by boydj** [comment]
`default['hashicorp-vault']['options']['archive_url'] = 'https://hashicorp.mirror.corporate.com/consul/%{version}/%{basename}'
`

Works for me.

**Comment by johnbellone** [comment]
What @boydj said should work as expected. This is more than a little confusing, but it is keyed off the name of the cookbook (which is hashicorp-vault).

**Comment by legal90** [comment]
@johnbellone Agree. But probably it would be good describe it in README.md. All this "poise" magic is not obvious for users, IMO.

**Comment by johnbellone** [comment]
@coderanger and I had this conversion a few weeks ago. I am going to poke him and see if its something we can write for once inside of the library's readme and link to it.
