### ISSUE TITLE
Vault 0.2.0 - Does not like tls_disable entered as empty string

### ISSUE THREAD

**Issue by zarry** [johnbellone/vault-cookbook#8]
According to the documentation this field should be omitted if it is not planned on being used.  With the current implementation, vault is failing to start because tls_disable is ""

```
% sudo su -c "vault server -config=/home/vault/.vault.json" -s /bin/sh vault
Error detecting advertise address: tls_disable: strconv.ParseBool: parsing "": invalid syntax
Error initializing core: missing advertisement address
```

The documentation on strconv.ParseBool makes it look like we should set the value to false inside of a string.

http://golang.org/pkg/strconv/#ParseBool

Again, I will likely get a PR for this.

**Comment by chrisferry** [comment]
:+1: Can this get merged in?  Would love to have tls enabled.

**Comment by johnbellone** [comment]
It needs to be re-based.
