### ISSUE TITLE
Can we get a new minor release?

### ISSUE THREAD

**Issue by boydj** [johnbellone/vault-cookbook#83]
A new minor release to supermarket would be helpful since 0.6.2 vault is not in the current release.

**Comment by vijaybandari** [comment]
@boydj you can install any version version with the supermarket cookbook. Just set the attribute node['hashicorp-vault']['version'] to '0.6.2'

**Comment by boydj** [comment]
I don't think that worked for me when I tried. The checksums are not present in the released code.

**Comment by vijaybandari** [comment]
yeah, in that case it won't do any checksum check and just downloads. We installed the latest version with the 2.4.0

**Comment by johnbellone** [comment]
@legal90 Do we want to wait for #76 and #86 before cutting a minor release?

**Comment by legal90** [comment]
@johnbellone I think we should complete #86 only. #76 is pretty big and requires more efforts.

**Comment by vijaybandari** [comment]
Can you guys cut a new release as #86 is completed.

**Comment by legal90** [comment]
I'm sorry for so huge delay. Finally, v2.5.0 is released and published:
https://supermarket.chef.io/cookbooks/hashicorp-vault/versions/2.5.0
