### ISSUE TITLE
Service Logging

### ISSUE THREAD

**Issue by askmike1** [johnbellone/vault-cookbook#89]
Is there a way to have the system service (/etc/init.d/vault) send its output to a log file?

**Comment by legal90** [comment]
It should work already. Logs are sent to `/var/log/vault.log` by default.
https://github.com/johnbellone/vault-cookbook/blob/cf1d96306e72b0894a1355eb039a9c3f47e7074b/templates/default/sysvinit.service.erb#L67

**Comment by askmike1** [comment]
Interesting, it doesn't seem to be logging there for me by default. In fact my /etc/init.d/vault script looks more like the following:

`#!/bin/sh`
`# Init script for vault generated by poise-service`
`#`
`### BEGIN INIT INFO`
`# Provides: vault`
`# Required-Start: $remote_fs $syslog`
`# Required-Stop: $remote_fs $syslog`
`# Default-Start: 2 3 4 5`
`# Default-Stop: 0 1 6`
`# Short-Description: Init script for vault`
`# Description: Init script for vault`
`### END INIT INFO`
``
`_start() {`
`  /opt/chef/embedded/bin/ruby <<EOH`
`require 'etc'`
`pid_file = "/var/run/vault.pid"`
`File.unlink(pid_file) if File.exist?(pid_file)`
`if Process.fork`
`  sleep(1) until File.exist?(pid_file)`
`else`
`  Process.daemon(true)`
`  Dir.chdir("/var/run/vault")`
`  IO.write(pid_file, Process.pid)`
`  ent = Etc.getpwnam("consul")`
`  if Process.euid != ent.uid || Process.egid != ent.gid`
`    Process.initgroups(ent.name, ent.gid)`
`    Process::GID.change_privilege(ent.gid) if Process.egid != ent.gid`
`    Process::UID.change_privilege(ent.uid) if Process.euid != ent.uid`
`  end`
`  Kernel.exec(*["/opt/vault/0.6.4/vault", "server", "-config=/etc/vault/vault.json"])`
`  exit!`
`end`
`EOH`
`}`

**Comment by legal90** [comment]
@askmike1 What cookbook version are you using?
The custom template for `sysvinit` provider has been added in v2.4.0 (https://github.com/johnbellone/vault-cookbook/pull/51)

**Comment by askmike1** [comment]
Wow, didn't even realize I was on an older version of the cookbook... thanks!
