### ISSUE TITLE
No storage config?

### ISSUE THREAD

**Issue by krogebry** [johnbellone/vault-cookbook#95]
I'm trying to configure storage options here, but I can't seem to get it to work.

I did this thinking it would magically work:

```
node.default['hashicorp-vault']['config']['storage'] = {
    'path' => node['stack_name'],
    'address' => 'consul.nmgcloudapps.com:8500'
}
```

I get this:

```
/tmp/local-mode-cache/cache/cookbooks/hashicorp-vault/recipes/default.rb:

 16:  end
 17:  
 18:  config = vault_config node['hashicorp-vault']['config']['path'] do |r|
 19:    owner node['hashicorp-vault']['service_user']
 20:    group node['hashicorp-vault']['service_group']
 21:  
 22:    if node['hashicorp-vault']['config']
 23>>     node['hashicorp-vault']['config'].each_pair { |k, v| r.send(k, v) }
 24:    end
 25:    notifies :reload, "vault_service[#{node['hashicorp-vault']['service_name']}]", :delayed
 26:  end
```

I'm going to try some things locally on this project, we'll see where this goes.

Am I doing something wrong here?

**Comment by Ginja** [comment]
That's because `['storage']` isn't a valid config parameter. The key after `['config']` has to be a valid parameter.

```
address
cluster_address
tls_disable
tls_cert_file
tls_key_file
cache_size
disable_cache
disable_mlock
default_lease_ttl
max_lease_ttl
statsite_addr
statsd_addr
backend_type
backend_options
habackend_type
habackend_options
telemetry_options
```

Example, setting the habackend_type to consul:

```
node.default['hashicorp-vault']['config']['habackend_type'] = 'consul'
```

Refer to the Vault docs [here](https://www.vaultproject.io/docs/configuration/).

**Comment by krogebry** [comment]
Okay, so what you're saying is that this:

```
storage "consul" {
  address = "127.0.0.1:8500"
  path    = "vault"
}
```

Is actually *habackend_type* and I should be using that and habackend_options?  I'll give it a try and see how it works.  Thanks for the feedback.

**Comment by Ginja** [comment]
👍 

Closing the issue.
