### ISSUE TITLE
vault-ssh-helper inclusion in this cookbook

### ISSUE THREAD

**Issue by tanner-bruce** [johnbellone/vault-cookbook#98]
Hi, I'm curious if you feel that this cookbook is the right place to include the installation of https://releases.hashicorp.com/vault-ssh-helper/

If so, I'm willing to put in the work, otherwise I will create a new cookbook for it

**Comment by Ginja** [comment]
I'd say since this is supplementary and not to do with the management of Vault itself that is should probably live in your wrapper cookbook of this cookbook.

**Comment by tanner-bruce** [comment]
Well, in my humble opinion, it would not belong in a wrapper cookbook either. If it does not belong here then I suppose a separate application cookbook is the answer.

I would argue that this is similar to the Consul web UI which was only recently removed from the Consul cookbook, and at that only because the functionality was added in to Consul itself. It _is_ a bit of a grey area in that it is directly related to Vault, but not directly part of it, I can see both including it and not.

**Comment by Ginja** [comment]
I do see both points as well, but unlike the Consul UI (which almost everyone wanted, and was semi-related to the management of Consul), Vault's SSH backend is optional and is not related to the management of the service. This cookbook also provides no way to manage backends. So to have a specific backend tool included in this cookbook would be a bit odd. 

An application/wrapper cookbook, depends if you want to share it with the community. Cool utility though! May look at using it myself.
